title: "Sooriya Senthilkumar"
author: "Sooriya Senthilkumar"
description: "Georgia Tech CS Student | FinTech Enthusiast | Aspiring Software Engineer"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"


show_excerpts: true
show_frame: true
show_sidebar: false
minimal: false


navigation:
  - {file: "index.html", title: "Home"}
  - {file: "archive.html", title: "Projects"}
  - {file: "resume.html", title: "Resume"}

external:
  - {title: Mail, icon: envelope, url: "mailto:ssenthil39@gatech.edu"}
  - {title: Github, icon: github, url: "https://github.com/sooriya14"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/sooriya-s"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

plugins:
 - jekyll-feed
